// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: SquareLine_Bauer

#ifndef _I80_CONTROLLER_EXAMPLE_MAIN_H
#define _I80_CONTROLLER_EXAMPLE_MAIN_H

#ifdef __cplusplus
extern "C"
{
#endif



#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif  //_I80_CONTROLLER_EXAMPLE_MAIN_H
